Dev-FE-2/toy-project3-team4

.github/ISSUE_TEMPLATE/bugfix.yml
.github/ISSUE_TEMPLATE/docs.yml
.github/ISSUE_TEMPLATE/feature.yml
.github/ISSUE_TEMPLATE/fix.yml
.github/ISSUE_TEMPLATE/refactor.yml
.github/ISSUE_TEMPLATE/settings.yml

- 이슈 템플릿 추가 
-  🐞 BugFix
- 📃 Docs
- ✨ Feature
- 🔨 Fix
- 🔨 Refactor
- ⚙ Settings
- 없음

[Settings] issue 템플릿 생성

---

tsconfig.app.json

**tsconfig에서 프로젝트 절대경로 설정 추가**
- tsconfig에서 프로젝트 절대경로 설정 추가

settings: tsconfig에서 프로젝트 절대경로 설정 추가 (#8)

---

tsconfig.app.json
vite.config.ts

**[프로젝트 절대경로 설정을 위한 vite.config.ts 수정 (#10) ]**
- 프로젝트 절대경로 설정을 위한 vite.config.ts 수정

[Settings] 프로젝트 절대경로 설정을 위한 vite.config.ts 수정

---

src/components/core/ProfileImage/ProfileImage.styles.ts
src/components/core/ProfileImage/ProfileImage.tsx
src/components/layout/Logo/Logo.styles.ts
src/components/layout/Logo/Logo.tsx
src/components/layout/MobileHeader/MobileHeader.styles.ts
src/components/layout/MobileHeader/MobileHeader.tsx
src/components/layout/MobileNavBar/MobileNavBar.styles.ts
src/components/layout/MobileNavBar/MobileNavBar.tsx
src/components/layout/SideNavBar/SideNavBar.styles.ts
src/components/layout/SideNavBar/SideNavBar.tsx
src/constant/navigation.ts
src/layout/Layout.styles.ts
src/layout/Layout.tsx
src/routes/ProtectedRoute.tsx

**반응형 레이아웃 UI 피드백 반영**
- 레이아웃 관련 컴포넌트 범위 내 피드백 반영

[🔨 Fix] 반응형 레이아웃 UI 피드백 반영

---

package-lock.json
package.json

- 리액트 아이콘 라이브러리 설치
- package.json
- package-lock.json

[⚙ Settings] react-icons 라이브러리 설치

---

src/GlobalStyle.ts

**[globalStyle의 폰트 사이즈 기준 변경]**
- globalStyle의 폰트 사이즈 기준 변경
- 모바일 퍼스트 - 10px 기준 : 데스크탑 버전의 10rem = 11px, 모바일 버전의 10rem = 10px

[Style] globalStyle의 폰트 사이즈 기준 변경

---

src/styles/token/font.ts

**font 디자인 토큰 수정**
- heading 폰트 css 값 정의
- font-size, font-weight 정의
- styles/token/font.ts 파일 수정과 사용하는 변수 외 모두 제거
```ts
export const font = {
size: {
heading: '2.4rem',
subHeading: '2.0rem',
paragraph: '1.6rem',
info: '1.4rem',
min: '1.4rem',
values: {
heading: 24,
subHeading: 20,
paragraph: 16,
info: 14,
min: 14,
},
},
family: "'Noto Sans KR', sans-serif",
weight: {
heading: 600,
subHeading: 500,
},
};
```

[🔨 Fix] font 디자인 토큰 업데이트

---

.stylelintrc.json
package-lock.json
package.json
vite.config.ts

**Stylelint 설치와 styled-components 관련 라이브러리 설치**
- Stylelint를 설치하여 css 코드 품질 향상 및 일관성 있는 css 코드 스타일 관리
- css-in-js 에서도 stylelint가 동작되도록 추가 라이브러리 설치 
- stylelint: 스타일시트 코드의 린팅을 담당하는 핵심 도구
- stylelint-config-standard: 표준 스타일링 규칙을 제공
- stylelint-config-styled-components: styled-components에 특화된 린팅 규칙을 제공
- @stylelint/postcss-css-in-js: styled-components의 CSS-in-JS 구문을 처리
```typescript
// vite.config.ts
import stylelint from 'vite-plugin-stylelint'; // 추가
export default defineConfig({
plugins: [react(), stylelint({})], // 추가
// ...
});
``` 
```json
"lint-staged": {
"*.{js,ts,jsx,tsx}": [
"eslint --fix",
"stylelint --fix",
"prettier --write"
],
"*.{css,scss}": [
"stylelint --fix",
"prettier --write"
],
}
```  
- lint:style: 모든 JavaScript 및 …

[⚙ Settings] Stylelint 설치와 styled-components 관련 린트 설정

---

package-lock.json
package.json
src/components/core/Loader/LoaderWrapper.styles.ts
src/components/core/Loader/LoaderWrapper.tsx
src/components/core/Loader/index.ts
src/components/core/index.ts
src/layout/Layout.styles.ts

1. react-spinners 설치
2. 로딩 컴포넌트 추가
- FadeLoader를 사용해서 LoaderWrapper 컴포넌트를 만들었습니다.
- LoaderWrapper에 isLoading과 text Props를 전달할 수 있습니다.
- text는 필요에 따라 넣으시면 됩니다.
사용예시 :
```tsx
import { LoaderWrapper } from '@/components';
import { useState } from 'react';
const HomePage = () => {
const [isLoading, setIsLoading] = useState(true);
return (
<LoaderWrapper isLoading={isLoading} text="로딩중...">
<div>Home 페이지 입니다</div>
</LoaderWrapper>
);
};
export default HomePage;
```

[✨ Feature] 로딩 컴포넌트(스피너) 추가

---

src/hooks/useAuth.ts
src/routes/routeConfig.tsx
src/store/index.ts
src/store/userStore.ts

- 로그인 되어있는 상태에서, 인증필요 페이지의 주소로 직접 접근하면 페이지 접속이 불가한 오류 수정
- userStore에 각 action 이름 설정

[🔨 Fix] 로그인 상태에 따른 route 오류 및 userStore 액션 이름 설정

---

src/api/service/user/userService.ts
src/utils/dbUtil.ts
src/utils/index.ts

firestore와 연동해서 crud를 담당하는 공통 유틸함수 개발
이렇게 각 도메인별 service를 구성하고,
tanstack-query와 연동한 도메인별 커스텀훅을 구성하면 되지 않을까 싶습니다.

[✨ Feature] firestore 관련 공통 유틸함수 개발

---

src/styles/token/colors/semantic.ts
src/styles/token/width.ts

**디자인 토큰 업데이트**
- styles/width 토큰 추가
- 프라이머리 색상과 호버 색상 수정
- styles/width 토큰 추가
```typescript
const width = {
feed: '47.0rem',
content: '72.0rem', // 논의 했던 default 변수에서 이름을 구체적으로 바꿨습니다.
desktop: '102.4rem',
};
export { width };
``` 
- before
- after

[⚙ Settings] styles/width 토큰 추가와 primary 색상 수정

---

src/constant/interests.ts
src/hooks/index.ts
src/hooks/useInterestSelection.ts
src/pages/InterestPage/InterestPage.styles.ts
src/pages/InterestPage/InterestPage.tsx
src/types/userTypes.ts

관심사 선택 후 저장 및 수정 기능 개발
관심사 선택 유도는 별도의 이슈로 생성하여 추후 진행하겠습니다.

[✨ Feature] 관심사 선택 기능 개발

---

src/components/core/Input/Input.styles.ts
src/components/core/Input/Input.tsx
src/components/core/Input/index.ts
src/components/core/Textarea/Textarea.styles.ts
src/components/core/Textarea/Textarea.tsx
src/components/core/Textarea/index.ts
src/components/core/index.ts

**공통 컴포넌트 Input과 Textarea 컴포넌트 생성**
- Input 컴포넌트
- Textarea 컴포넌트
```tsx
<Input 
type='search' 
value={inputValue} 
placeholder='검색' 
onChange={handleChange} 
isBorder={false} 
bgColor="#ebeef1" 
/>
``` 
```tsx
<Input 
type='search' 
name='search' 
value={inputValue} 
placeholder='검색' 
onChange={handleChange} 
/>
``` 
```tsx
<Textarea value={inputValue} placeholder='검색' onChange={handleChange} />
``` 

[✨ Feature] Input, Textarea 컴포넌트 생성

---

package-lock.json
package.json
src/components/core/Switch/Switch.styles.ts
src/components/core/Switch/Switch.tsx
src/components/core/Switch/index.ts
src/components/core/index.ts
src/pages/UpsertPlaylistPage/UpsertPlaylistPage.styles.ts
src/pages/UpsertPlaylistPage/UpsertPlaylistPage.tsx

플레이리스트 생성/수정 페이지 마크업
input, textarea는 #72 PR 머지되면, 기능 구현 시 적용해서 수정하겠습니다.

[✨ Feature] 플레이리스트 생성/수정 페이지 마크업

---

src/components/core/RoundTag/RoundTag.tsx
src/components/core/TagList/TagList.styles.ts
src/components/core/TagList/TagList.tsx

[Fix] 누락된 taglist 파일 추가

---

src/components/layout/desktop/sidebar/MoreNavItems/MoreNavItems.tsx

**사이드바 더보기 버튼 클릭 시 드롭다운 메뉴 이슈 수정**
포탈에 전달되도록 하는 dom 요소 id 오타로 에러가 나서 수정합니다.
- 수정 완료
- 수정 전

[🐞 BugFix] 사이드바 더보기 드롭다운 메뉴 에러 수정

---

src/components/layout/desktop/sidebar/DesktopSearch/DesktopSearch.tsx
src/components/layout/desktop/sidebar/MainNavItems/MainNavItems.tsx
src/components/layout/mobile/MobileSearch/MobileSearch.tsx
src/components/search/SearchForm/SearchForm.tsx
src/components/search/SearchHistory/SearchHistory.tsx
src/store/index.ts
src/store/searchHistoryStore.ts

**사용자 인터렉션에 대한 UI 변화를 위한 검색폼 수정 #80 **
- 사용자 인터렉션에 대한 UI 변화를 위한 검색폼 수정
- 검색어 확인,저장 및 제거를 위한 스토어 개발

[FIX] 사용자 인터렉션에 대한 UI 변화를 위한 검색폼 수정

---

src/styles/index.ts
src/styles/token/colors/semantic.ts
src/styles/token/font.ts
src/styles/token/index.ts
src/styles/token/padding.ts

[🔨 Fix] 디자인 토큰 업데이트

---

src/components/button/LikeButton.tsx
src/components/button/index.ts
src/components/feeds/Feed/Feed.tsx
src/components/feeds/InteractionBar/InteractionBar.styles.ts
src/components/feeds/InteractionBar/InteractionBar.tsx
src/components/feeds/InteractionBar/index.ts
src/components/feeds/index.ts
src/hooks/user/index.ts
src/hooks/user/useFetchMyUserInfo.ts

[✨ Feature] Feed Interaction bar 컴포넌트와 기능 구현

---

src/api/service/playlist/playlistService.ts
src/api/service/user/userService.ts
src/components/card/ExplorePlayListCard/ExplorePlayListCard.tsx
src/components/card/ProfileCard/ProfileCard.styles.ts
src/components/card/ProfileCard/ProfileCard.tsx
src/components/core/Tab/Tab.styles.ts
src/components/core/Tab/Tab.tsx
src/components/core/Tab/index.ts
src/components/search/SearchHistory/SearchHistory.tsx
src/pages/ProfilePage/ProfilePage.styles.ts
src/pages/ProfilePage/ProfilePage.tsx
src/pages/SearchPage/SearchPage.styles.ts
src/pages/SearchPage/SearchPage.tsx

**검색, 프로필 페이지 개발**
- 검색, 프로필 페이지 개발

[FEAT] 검색, 프로필 페이지 개발

---

README.md

[📃 Docs] 프로젝트 정리한 README 파일 업데이트

---

src/components/button/IconButton.tsx
src/components/button/IconLink.tsx
src/styles/iconStyle.ts
src/styles/index.ts

- IconButton, IconLink 두 컴포넌트의 css를 공통으로 묶어서 관리합니다.
- icon padding이 적용되어 라인이 틀어지는 것을 방지합니다.

[🔨 Refactor] 공통 css를 사용하는 IconButton, IconLink 컴포넌트 리팩토링 및 css 수정

---

src/components/layout/desktop/sidebar/SideNavBar/SideNavBar.tsx
src/constant/navItems.ts

- 유저 팔로우 / 팔로잉 기능 구현이 완성된 이후에 노출하기 위해 현재 네비게이션에서 UI 제거
- 사이드바에서 팔로우 네비 메뉴 UI 제거

[☕️ Chore] 팔로잉 플레이리스트 네비게이션 임시 제거

---

package-lock.json
package.json
src/App.tsx

- 캐시 문제로 캐시된 데이터 상태 확인이 필요하여 devtool 설치
공식문서 
https://tanstack.com/query/latest/docs/framework/react/devtools

⚙ Settings] tanstack/react-query-devtools 설치 및 설정

---

package-lock.json
package.json
src/components/video/VideoPlayer/VideoPlayer.styles.ts
src/components/video/VideoPlayer/VideoPlayer.tsx
src/pages/PlaylistViewPage/PlaylistViewPage.tsx

플레이리스트 상세페이지에서 영상이 자동으로 재생되도록 구현

[✨ Feature] 플레이리스트 자동재생 기능 구현
